### ISSUE TITLE
Build Python Library for Ubuntu?

### ISSUE THREAD

**Issue by Hazeline2018** [trinamic/TMC-API#26]
Hello,

I'm using TCM drivers to control Stepper motors on my project. I'm using Ubuntu 20.04 on Jetson Nano dev board. I'd like to build a Python library or package so that I can utilize the TMC-API in my environment. Could you please advise the procedure? And if there is a ready Python lib for use or a work in the plan? I searched quite a while and couldn't find one.

Thanks,
Terry

**Comment by trinamic-ed** [comment]
Hi,

we started a Python project to access our eval boards and modules via python here: https://github.com/trinamic/PyTrinamic
It is also available at https://pypi.org/project/pytrinamic/

In the moment we are working on a major update here in this branch: 

https://github.com/trinamic/PyTrinamic/tree/feature_feature_hierarchy_v2

It is available with pypi by "pip install pytrinamic==0.2.0rc1"

If there are more ideas for additional functions, we can check and add it to the python package.

Regards,
     Enrico
