### ISSUE TITLE
TMC6100 api is using int type assuming it's 32 bit

### ISSUE THREAD

**Issue by slava-medacuity** [trinamic/TMC-API#33]
int should be changed to int32_t explicitly
`
int tmc6100_readInt(uint8_t motor, uint8_t address) -> int32_t tmc6100_readInt(uint8_t motor, uint8_t address)

void tmc6100_writeInt(uint8_t motor, uint8_t address, int value) -> void tmc6100_writeInt(uint8_t motor, uint8_t address, int32_t value)
`

**Comment by trinamic-ASU** [comment]
Thank you for your feedback. We have updated it.
