### ISSUE TITLE
Redefinition of ARRAY_SIZE macro

### ISSUE THREAD

**Issue by dennismalcorps** [trinamic/TMC-API#36]
Hello everyone,

while working on integrating the TMC2300 into one of our projects, we got a redefinition warning of the above mentioned macro, because our microcontroller sdk implements this too. After a quick glimpse into your code, it turns out there is a missing #ifndev...#endif around ARRAY_SIZE.

**Comment by trinamic-ASU** [comment]
Thank you for the suggestion and your valuable feedback. We have fixed this issue now.
