### ISSUE TITLE
Incomplete defines

### ISSUE THREAD

**Issue by riggs** [trinamic/TMC-API#6]
https://github.com/trinamic/TMC-API/blob/5131ebe041dbab844001b6e4213e62a5ae2af2e3/tmc/ic/TMC5160/TMC5160_Fields.h#L943-L948

This looks like an error in generation. Is there a reason these fields aren't defined?

**Comment by Lionheart1810** [comment]
This error roots indeed from the autogeneration we used back in the day.
Now we use different tooling and this should not be an issue anymore.

**Comment by trinamic-LH** [comment]
Fixed in cc9a2d323547f380691b56f240836fc69017e6e5 - thanks @riggs for fixing it yourself 👍
